version: '3'
services:
  website:
    image: docker.pkg.github.com/vijaystroup/vijaystroupcom/vijaystroup.com:latest
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.website-http.rule=Host(`vijaystroup.com`, `www.vijaystroup.com`)
        - traefik.http.routers.website-http.entrypoints=http
        - traefik.http.routers.website-http.middlewares=https-redirect
        - traefik.http.routers.website-https.rule=Host(`vijaystroup.com`, `www.vijaystroup.com`)
        - traefik.http.routers.website-https.entrypoints=https
        - traefik.http.routers.website-https.tls=true
        - traefik.http.routers.website-https.tls.certresolver=le
        - traefik.http.services.website.loadbalancer.server.port=80
networks:
  traefik-public:
    external: true
