version: '3'
services:
  web:
    image: docker.pkg.github.com/vijaystroup/vijaystroupcom/vijaystroup.com:latest
    environment:
      - EMAIL_USER=${EMAIL_USER?Variable not set}
      - EMAIL_PASS=${EMAIL_PASS?Variable not set}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.web-http.rule=Host(`example.com`)
        - traefik.http.routers.web-http.entrypoints=http
        - traefik.http.routers.web-http.middlewares=https-redirect
        - traefik.http.routers.web-https.rule=Host(`example.com`)
        - traefik.http.routers.web-https.entrypoints=https
        - traefik.http.routers.web-https.tls=true
        - traefik.http.routers.web-https.tls.certresolver=le
        - traefik.http.services.web.loadbalancer.server.port=80
  ucf-fe:
    image: docker.pkg.github.com/vijaystroup/ucf-fe/ucf-fe:latest
    environment:
      - MODULE_NAME=app
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.ucf_fe-http.rule=Host(`ucffe.example.com`)
        - traefik.http.routers.ucf_fe-http.entrypoints=http
        - traefik.http.routers.ucf_fe-http.middlewares=https-redirect
        - traefik.http.routers.ucf_fe-https.rule=Host(`ucffe.example.com`)
        - traefik.http.routers.ucf_fe-https.entrypoints=https
        - traefik.http.routers.ucf_fe-https.tls=true
        - traefik.http.routers.ucf_fe-https.tls.certresolver=le
        - traefik.http.services.ucf_fe.loadbalancer.server.port=80
networks:
  traefik-public:
    external: true
